/*
  # Add fallback fields to jd_drafts table

  1. New Fields
    - `has_fallback` (boolean) - indicates if this draft was created in fallback mode
    - `is_ai_generated` (boolean) - indicates if the content was generated by AI
    - `input_summary` (text) - short descriptive summary of the input type

  2. Updates
    - Add default values for new fields
    - Update existing records to have proper fallback status
*/

-- Add new columns to jd_drafts table
DO $$
BEGIN
  -- Add has_fallback column
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'jd_drafts' AND column_name = 'has_fallback'
  ) THEN
    ALTER TABLE jd_drafts ADD COLUMN has_fallback boolean DEFAULT false;
  END IF;

  -- Add is_ai_generated column
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'jd_drafts' AND column_name = 'is_ai_generated'
  ) THEN
    ALTER TABLE jd_drafts ADD COLUMN is_ai_generated boolean DEFAULT true;
  END IF;

  -- Add input_summary column
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'jd_drafts' AND column_name = 'input_summary'
  ) THEN
    ALTER TABLE jd_drafts ADD COLUMN input_summary text;
  END IF;
END $$;

-- Update existing records to have proper input_summary based on input_type
UPDATE jd_drafts 
SET input_summary = CASE 
  WHEN input_type = 'website' THEN 'Brief + link provided'
  WHEN input_type = 'manual' THEN 'Job brief provided'
  WHEN input_type = 'upload' THEN 'JD file uploaded'
  WHEN input_type = 'link' THEN 'Reference job link provided'
  ELSE 'Job description input provided'
END
WHERE input_summary IS NULL;

-- Make input_summary NOT NULL after updating existing records
ALTER TABLE jd_drafts ALTER COLUMN input_summary SET NOT NULL;

-- Create index for performance on new fields
CREATE INDEX IF NOT EXISTS idx_jd_drafts_has_fallback ON jd_drafts USING btree (has_fallback);
CREATE INDEX IF NOT EXISTS idx_jd_drafts_is_ai_generated ON jd_drafts USING btree (is_ai_generated);